variable "account_id" {
  type        = string
  description = "The account ID of the master account"
}

variable "metadata" {
  type        = string
  description = "The identity provider metadata generated by Okta"
}

variable "max_session_duration" {
  type        = number
  default     = 12
  description = "The maximum session duration for the role"
}

variable "name" {
  type        = string
  description = "A name for the default platform admin role"
}

variable "postfix" {
  type        = bool
  default     = true
  description = "Postfix the admin role and policy names with Role and Policy"
}

variable "tags" {
  type        = map(string)
  description = "A mapping of tags to assign to the resources"
}
