variable account_id {
  type        = string
  description = "The account ID of the master account"
}

variable metadata {
  type        = string
  description = "The identity provider metadata generated by Okta"
}

variable name {
  type        = string
  description = "A name for the default platform admin role"
}

variable tags {
  type        = map(string)
  description = "A mapping of tags to assign to the resources"
}
