---
name: Terraform

on:
  pull_request:
    paths:
    - "**/*.tf"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: fmt
          tf_actions_comment: true

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: init
          tf_actions_comment: true
          tf_actions_cli_credentials_token: ${{ secrets.CB_TERRAFORM_TOKEN }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        env:
          AWS_DEFAULT_REGION: eu-west-1
        with:
          tf_actions_version: latest
          tf_actions_subcommand: validate
          tf_actions_comment: true

  terraform-tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v3.0.3

  terraform-documentation:
    runs-on: ubuntu-latest
    needs: [terraform-fmt, terraform-tfsec, terraform-validate]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Update module usage docs and push any changes back to PR branch
        uses: Dirrk/terraform-docs@v1.0.8
        with:
          tf_docs_args: '--sort-inputs-by-required'
          tf_docs_git_commit_message: 'terraform-docs: Update module usage'
          tf_docs_git_push: 'true'
          tf_docs_output_file: README.md
          tf_docs_output_method: inject
